### ISSUE TITLE
README.md ausformulieren

### ISSUE THREAD

**Issue by Sofia911** [Fuenfgeld/DMA2022DataProjectC#39]
- [x]  Verlinkungen zu anderen Gruppen
- [x]  Verlinkung zum Video
- [x]  Kurze Beschreibung der Forschungsfrage ?
- [x] Verlinkung Analyse und ETL Notebook in Installation
- [x] Ergebnisse kurz erläutern

**Comment by Fuenfgeld** [comment]
Hier sollte noch eine Kurze projekt Beschreibung rein. Das Readme sollte wie ein Abstract sein. https://en.wikipedia.org/wiki/Abstract_(summary).
