### ISSUE TITLE
Daten-Repoduzierbarkeit

### ISSUE THREAD

**Issue by lukasbu123** [Fuenfgeld/DMA2022DataProjectC#41]
- [x] Herstellen von hash-werten der Roh Daten (CSV-Dateien)
- [x] Dokumentierung Wiki
- [x] Prüfung der Werte im ETL-Prozess

**Comment by niklasbuechner** [comment]
Ich habe die Dokumentation hier https://github.com/Fuenfgeld/DMA2022DataProjectC/wiki/Datenintegrit%C3%A4t angepasst.
