### ISSUE TITLE
Video erstellen

### ISSUE THREAD

**Issue by Sofia911** [Fuenfgeld/DMA2022DataProjectC#42]
* Datenmanagementplan ist Inhaltsverzeichnis (alle anderen Dateien werden darin referenziert)
* Highlights/Schwerpunkte herauspicken (z.B nur Datenqualität prüfen, wo wir viel Zeit investiert haben)
* zusammenhängende Geschichte erzählen (z.B. Dialog zwischen Experte & Laie)
* muss nicht zwangsläufig eine Präsentation sein
* Beispiele: https://www.youtube.com/c/DMEA-Health
* ca. 7 Min.
* Ziel: Projekt darstellen, für jemand, der noch nie etwas von unserem Projekt gehört hat
* wie würde ich es meiner Mutter erklären?
* powerpoint ist zu einfach
* Warum haben wir das so umgesetzt? z.B. Datenschutz
* Forschungsfrage & abschließendes Ergebnis mit einbeziehen

**Comment by lukasbu123** [comment]
Skript in #44 
Meeting von 07.07.22
- Video:
  -> 2 bis 3 Highlights setzen
  -> Auf Planung & Datenmanagementplan eingehen
  -> Präsentieren, was sind die Herausforderungen, Lösung, Umsetzung und immer erklären warum
  -> Prozess aufzeigen, wie wir zur Pipeline gekommen sind
  -> Forschungsfrage & Auswertung mit aufnahmen

**Comment by niklasbuechner** [comment]
Stand 07.07: Länge gerne auch 10 Minute +/- ein paar.

**Comment by niklasbuechner** [comment]
Tool: PowerPoint
Visueller Teil: @niklasbuechner 
Audio Teil / Skript: @Sofia911 @lukasbu123

**Comment by niklasbuechner** [comment]
Die Arbeiten zu diesem Issue finden auf dem `video` Branch statt: https://github.com/Fuenfgeld/DMA2022DataProjectC/tree/video
