### ISSUE TITLE
Zweites Videoskript erstellen

### ISSUE THREAD

**Issue by Sofia911** [Fuenfgeld/DMA2022DataProjectC#44]
Inspirationen:
https://www.youtube.com/c/DMEA-Health

**Comment by niklasbuechner** [comment]
- Mögliche Geschichte:
    - Forscher ... möchte eine Forschungsfrage beantworten
    - Dazu benötigt er eine Datenverarbeitungspipeline, weshalb er zu uns kommt.
    - Wir stellen ihm eine gut funktionierende Pipeline, damit er sich um die eigentliche Analyse kümmern kann und sich keine Gedanken rund um die Technik machen muss.
    - => Wir sind Experten für Datenverarbeitung und fokusieren uns nicht auf die Analyse.
    - Wir wollen auch die Reproduzierbarkeit der Pipeline hervorheben.

**Comment by niklasbuechner** [comment]
Feedback Herr Fünfgeld:
- Video:
  -> 2 bis 3 Highlights setzen
  -> Auf Planung & Datenmanagementplan eingehen
  -> Präsentieren, was sind die Herausforderungen, Lösung, Umsetzung und immer erklären warum
  -> Prozess aufzeigen, wie wir zur Pipeline gekommen sind
  -> Forschungsfrage & Auswertung mit aufnahmen
