### ISSUE TITLE
Rohdaten an zweitem Ort ablegen

### ISSUE THREAD

**Issue by niklasbuechner** [Fuenfgeld/DMA2022DataProjectC#49]
- [x] Dateien in Google Drive ablegen
- [x] In Datenschutzfolgeabschätzung dokumentieren

**Comment by lukasbu123** [comment]
closed in wiki [Datemschutzgrundverordnung9(https://github.com/Fuenfgeld/DMA2022DataProjectC/wiki/Datenschutzfolgeabsch%C3%A4tzung)
