### ISSUE TITLE
Datenflussdiagramm

### ISSUE THREAD

**Issue by Sofia911** [Fuenfgeld/DMA2022DataProjectC#52]
- [x] erster Entwurf
- [x] einzelne Skripte im Datenflussdiagramm verlinkern
- [x] Vergröberung, Anonymisierung kommen als einzelne Blöcke rein
- [x] Analyse ergänzen
- [x] auf eine Data Mart beschränken
- [ ] finalisieren
- [ ] Verlinkungen blau markieren

**Comment by lukasbu123** [comment]
-> Annonymisierung, etc, zu Boxen machen
    -> Dateien referenzieren
    -> GitHub rauswerfen
    -> Nur ein Data Mart, andere rauswerfen
    -> Daten kombinieren als extra Box ins Flussdiagramm
    -> Analyse noch als letzten Schritt hinzufügen (geht nicht um Schema, sondern als Schritt)
