### ISSUE TITLE
Mappingtabelle überarbeiten

### ISSUE THREAD

**Issue by Sofia911** [Fuenfgeld/DMA2022DataProjectC#57]
* Vorlage: https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Mappingtabelle_patients
* wie heißen die Ursprungsspalten in unserem neuen Datensatz

**Comment by niklasbuechner** [comment]
-> Mapping Tabelle besagt "transform to star schema"
  -> Mapping Tabelle bedeutet:
    -> Was sind die ursprungs Columns
    -> Wie heißen die Columns im transformierten Datenschema
    -> Für jede Tabelle in der Transformation
    -> Beispiel: https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Mappingtabelle_patients
    -> Kann eine Tabelle sein, alternativ ein Diagramm (ist aber
