### ISSUE TITLE
Videoskript erstellen

### ISSUE THREAD

**Issue by niklasbuechner** [Fuenfgeld/DMA2022DataProjectC#65]

**Comment by Sofia911** [comment]
Ergänzung: 

- Begründung warum man logging & unit Test braucht stärker betonen?

**Comment by niklasbuechner** [comment]
Begründungen für Logging & Datenvalidierung in der Pipeline:
- Nachvollziehbarkeit
- Pipeline ist transparent, man kann genau sehen was funktioniert hat und was nicht.
- Pipeline ist keine Blackbox
- Paul kann schon während der Forschungszeit seinem Chef transparent auf dem Laufenden halten und immer wieder seinen Forschungsstand präsentieren.
- Da mit medizinischen Daten gearbeitet wird, muss sehr genau gearbeitet werden. Vllt mit Ethik-Kommision begründen.
- Pipeline ist so gut, dass Paul sich auf seine Forschung konzentrieren kann und sich nicht mit der Technik auseinander setzen muss.

**Comment by niklasbuechner** [comment]
Wir werden von Test statt Unit-Tests sprechen, da es mehr Datentests sind und nicht Unit-Tests im IT-Sinne.

**Comment by Fuenfgeld** [comment]
Ich finde die Geschichte gut. ihr solltet noch erklären wo die Daten herkommen. Es könnten zB Daten aus der ePa der Patienten sein. https://www.bundesgesundheitsministerium.de/elektronische-patientenakte.html. Bei eurer Begründung braucht ihr noch das Problem das ihr mit eurem Logging und validierung lösen wollt. DH 

1. Projektbeschreibung. 
2. Ausgangslage (ePa als Datengrundlage)
3. Probleme/requirements des Projektes.
4. Eure technische Lösung
5. Ergebnis
