### ISSUE TITLE
Wie siehts bei euch aus?

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2022DataProjectC#75]
Hi Zusammen ihr habt jetzt noch eine Woche. Ist soweit alles klar bei euch? Werdet ihr fertig?

**Comment by lukasbu123** [comment]
Hallo Herr Fünfgeld,

wir haben zwar noch viele unserer Issues auf Projektboard, jedoch beziehen sich die meisten Aufgaben nur noch auf die Dokumentation und die Verlinkung zu den einzelnen Sektionen (Feinschliff: Beschreibungen ausfoumlieren). Die größere letzte Aufgabe ist noch das Video zu erstellen, welches wir bist Donnerstag aufjedefall hinbekommen sollten.
Falls Sie Zeit hätten würden wir uns über ein Feedback über folgende Punkte freuen: 

- Vorläufitges Skript/Ideen für das Video #65 
- Readme Datei des Proketes [hier](https://github.com/Fuenfgeld/DMA2022DataProjectC/blob/main/README.md) -> weitere Anmerkungen #39
